### ISSUE TITLE
Getting this to work with CSS variables

### ISSUE THREAD

**Issue by drewrawitz** [ads1018/postcss-emify#1]
Hello,

Just wanted to see if this could work with CSS variables, for example:

```css
:root {
  --spacing-med: 24px;
}

.l-container {
  padding-left: em(var(--spacing-med));
  padding-right: em(var(--spacing-med));
}
```

it currently outputs like so:
![js boilerplate 2017-01-03 12-33-39](https://cloud.githubusercontent.com/assets/5014932/21616796/fe38ef50-d1b0-11e6-9def-7c0cf148468c.png)

Thanks!
